# All hosts
all:

  hosts:

    # Localhost
    #"localhost":
    #  ansible_connection: local

    # Sample host to deploy to
    "mcsample":
      ansible_host: "mcsample.media.mit.edu"
      ansible_user: "myuser"
      ansible_ssh_private_key_file: "~/.ssh/mcsample"

      # Apache's ServerName; Apache and Ansible will expect the server to be
      # accessible publicly using this name
      apache2_server_name: "api.mediacloud.org"

      # Username to use for installing and running Media Cloud. Default is
      # "{{ ansible_user_id }}", i.e. Ansible user, for both localhost and remote
      # hosts.
      mediacloud_user: "mediacloud"

      # Home directory ($HOME) for user that will be running Media Cloud. Default
      # is "{{ ansible_env.HOME }}", i.e. Ansible user's home, for both localhost
      # and remote hosts.
      mediacloud_home: "/home/mediacloud"

      # Media Cloud root directory to check out the repository to. Default is
      # "../" (i.e. currently checked out repository as relative to "ansible/"
      # directory) on localhost and "{{ ansible_env.HOME }}/mediacloud" on remote
      # hosts.
      mediacloud_root: "/home/mediacloud/mediacloud"

      # Slack webhook token to use for sending out deployment notifications.
      slack_webhook_token: "RXXO9HP4Z/V2A2NB6S5/ZmXT6eUBpBBZp31htec3BLPg"

      # For more optional variables that you can set, please see "group_vars/" and
      # "host_vars/".

# Hosts that should be running PostgreSQL server
postgresql_server:

  hosts:
    "localhost":
    "mcsample":

# Hosts that should be running Media Cloud core services
core_services:

  hosts:
    "localhost":
    "mcsample":
    # "test":

# Hosts that should be running Solr shards
solr_servers:

  hosts:
    "mcsample":
    # "test":
