---

- name: Add pam_limits.so to /etc/pam.d/common-session
  lineinfile:
    dest: /etc/pam.d/common-session
    regexp: "^session\\s+required\\s+pam_limits.so$"
    line: "session required pam_limits.so"
    state: present
  become: true
  become_user: root
  tags:
    - pam-limits

- name: Add pam_limits.so to /etc/pam.d/sudo
  lineinfile:
    dest: /etc/pam.d/sudo
    regexp: "^session\\s+required\\s+pam_limits.so$"
    line: "session required pam_limits.so"
    state: present
  become: true
  become_user: root
  tags:
    - pam-limits

- name: Ensure that pam_limits configuration file exists
  copy:
    content: ""
    dest: "{{ limits_conf_path }}"
    force: no
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  tags:
    - pam-limits

# Each process is limited up to ~64 GB of memory
- name: Add hard virtual memory limit on pam_limits
  pam_limits:
    domain: "{{ mediacloud_user }}"
    limit_type: hard
    limit_item: as
    value: 67108864
    dest: "{{ limits_conf_path }}"
  become: true
  become_user: root
  when: "'solr_servers' not in group_names"  # only for hosts that won't run Solr because Solr would OOM
  tags:
    - pam-limits

- name: Increase soft open files limit on pam_limits
  pam_limits:
    domain: "{{ mediacloud_user }}"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: 65536
    dest: "{{ limits_conf_path }}"
  with_items:
    - "soft"
    - "hard"
  become: true
  become_user: root
  tags:
    - pam-limits
