---

- name: Test if GCC is installed
  stat:
    path: /usr/bin/gcc
  register: have_gcc
  tags:
    - system-packages

- name: Fail if GCC is not installed
  fail:
    msg: >
      As a dependency to Homebrew, you need to install Xcode (available as a free
      download from Mac App Store or from http://developer.apple.com/) and Xcode's
      "Command Line Tools" (open Xcode, go to "Xcode" -> "Preferences...", select
      "Downloads", choose "Components", click "Install" near the "Command Line Tools"
      entry, wait for a while.
  when: have_gcc.stat.executable is not defined or have_gcc.stat.executable == False
  tags:
    - system-packages

- name: Install system packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options }}"
    state: present
  with_items:
    - { name: coreutils, install_options: null }
    - { name: cpanminus, install_options: null }
    - { name: curl, install_options: null }
    - { name: gawk, install_options: null }
    - { name: hunspell, install_options: null }
    - { name: libyaml, install_options: null }
    - { name: logrotate, install_options: null }
    - { name: mecab, install_options: null }
    - { name: netcat, install_options: null }
    - { name: openssl, install_options: null }
    - { name: perl, install_options: null }
    - { name: python, install_options: null }
    - { name: python3, install_options: null }
    - { name: rabbitmq, install_options: null }
    - { name: re2, install_options: null }
    - { name: tidy-html5, install_options: null }
  tags:
    - system-packages

- name: Test if mecab-ipadic-neologd is installed
  stat:
    path: "{{ mecab_ipadic_neologd_path }}/sys.dic"
  register: mecab_ipadic_neologd_path_stat
  tags:
    - system-packages

- name: Install mecab-ipadic-neologd
  block:

    - name: Create temporary directory for mecab-ipadic-neologd
      tempfile:
        state: directory
        suffix: mecab-ipadic-neologd
      register: mecab_ipadic_neologd_tempdir
      tags:
        - system-packages

    - name: Download tarball with mecab-ipadic-neologd
      get_url:
        url: "{{ mecab_ipadic_neologd_url }}"
        dest: "{{ mecab_ipadic_neologd_tempdir.path }}/mecab-ipadic-neologd.tgz"
        checksum: "sha1:{{ mecab_ipadic_neologd_sha1sum }}"
      tags:
        - system-packages

    - name: Extract tarball with mecab-ipadic-neologd
      unarchive:
        remote_src: true
        src: "{{ mecab_ipadic_neologd_tempdir.path }}/mecab-ipadic-neologd.tgz"
        dest: "{{ mecab_ipadic_neologd_path }}"
        extra_opts: ["--strip-components=1"]
      tags:
        - system-packages

  when: mecab_ipadic_neologd_path_stat.stat.exists == False
